<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Admin extends Authenticatable
{
use HasApiTokens, HasFactory, Notifiable;

    protected $table = "tbl_admins";

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'admin_account',
        'admin_name',
        'cellphone',
        'password',
        'operator_id',
        'operator_name',
        'updated_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
    ];

    protected $appends = [
        'masked_phone'
    ]; // 在模型中添加此字段的访问器

    public function getMaskedPhoneAttribute()
    {
        return substr($this->cellphone, 0, 3) . '****' . substr($this->cellphone, -4);
    }
    // 添加方法确保密码自动哈希
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }

    public function toArray()
    {
        $data =  parent::toArray(); // TODO: Change the autogenerated stub
        unset($data["cellphone"]);
        $data["masked_phone"] = $this->masked_phone;
        $data["created_at"] = $this->created_at->format('Y-m-d H:i:s');
        $data["updated_at"] = $this->updated_at->format('Y-m-d H:i:s');
        return $data;
    }
}
